# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-23 00:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=60)),
                ('description', models.TextField(max_length=400)),
                ('travel_datefrom', models.TextField(max_length=400)),
                ('travel_dateto', models.TextField(max_length=400)),
                ('joined_by', models.ManyToManyField(related_name='joinedplans', to='login.User')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='login.User')),
            ],
        ),
    ]
