# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-23 01:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_plan',
            old_name='travel_dateto',
            new_name='enddate',
        ),
        migrations.RenameField(
            model_name='t_plan',
            old_name='travel_datefrom',
            new_name='startdate',
        ),
    ]
